CONTAINER AINODE_OBQ_BEND4STEREO
{
   NAME ainode_Obq_Bend4Stereo;

   INCLUDE GVbase;

   GROUP C4DAI_OBQ_BEND4STEREO_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_BEND4STEREO_SHADERIN {}
      AIPARAM C4DAIP_OBQ_BEND4STEREO_BENDMODE {}
      AIPARAM C4DAIP_OBQ_BEND4STEREO_LEFTCAMERA {}
      AIPARAM C4DAIP_OBQ_BEND4STEREO_CENTERCAMERA {}
      AIPARAM C4DAIP_OBQ_BEND4STEREO_RIGHTCAMERA {}
   }
}

