CONTAINER AINODE_OBQ_MEASUREDMATERIAL
{
   NAME ainode_Obq_MeasuredMaterial;

   INCLUDE GVbase;

   GROUP C4DAI_OBQ_MEASUREDMATERIAL_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_MEASUREDMATERIAL_FILENAME {}
      AIPARAM C4DAIP_OBQ_MEASUREDMATERIAL_RESOLUTION {}
      AIPARAM C4DAIP_OBQ_MEASUREDMATERIAL_SAMPLES {}
      AIPARAM C4DAIP_OBQ_MEASUREDMATERIAL_DIRECT_COLOR {}
      AIPARAM C4DAIP_OBQ_MEASUREDMATERIAL_DIRECT_SCALE {}
      AIPARAM C4DAIP_OBQ_MEASUREDMATERIAL_INDIRECT_COLOR {}
      AIPARAM C4DAIP_OBQ_MEASUREDMATERIAL_INDIRECT_SCALE {}
      AIPARAM C4DAIP_OBQ_MEASUREDMATERIAL_USEIMPORTANCESAMPLING {}
      AIPARAM C4DAIP_OBQ_MEASUREDMATERIAL_USEHALFS {}
      AIPARAM C4DAIP_OBQ_MEASUREDMATERIAL_USEJITTERS {}
      AIPARAM C4DAIP_OBQ_MEASUREDMATERIAL_BINMAXDIF {}
      AIPARAM C4DAIP_OBQ_MEASUREDMATERIAL_USEMIS {}
      AIPARAM C4DAIP_OBQ_MEASUREDMATERIAL_DIRECT_AOV {}
      AIPARAM C4DAIP_OBQ_MEASUREDMATERIAL_INDIRECT_AOV {}
   }
}

