CONTAINER AINODE_OBQ_TOONSIMPLE
{
   NAME ainode_Obq_ToonSimple;

   INCLUDE GVbase;

   GROUP C4DAI_OBQ_TOONSIMPLE_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_TOONSIMPLE_GLOBAL_COMPMODE {}
      AIPARAM C4DAIP_OBQ_TOONSIMPLE_GLOBAL_MULTBYLIGHTCOLOR {}
      AIPARAM C4DAIP_OBQ_TOONSIMPLE_AMBIENT_COLOR {}
      AIPARAM C4DAIP_OBQ_TOONSIMPLE_AMBIENT_SCALE {}
      AIPARAM C4DAIP_OBQ_TOONSIMPLE_AMBIENT_MULTAMBIENCE {}
      AIPARAM C4DAIP_OBQ_TOONSIMPLE_DIFFUSE_COLOR {}
      AIPARAM C4DAIP_OBQ_TOONSIMPLE_DIFFUSE_SCALE {}
      AIPARAM C4DAIP_OBQ_TOONSIMPLE_DIFFUSE_COVERAGE {}
      AIPARAM C4DAIP_OBQ_TOONSIMPLE_DIFFUSE_SOFTNESS {}
      AIPARAM C4DAIP_OBQ_TOONSIMPLE_HIGHLIGHT_COLOR {}
      AIPARAM C4DAIP_OBQ_TOONSIMPLE_HIGHLIGHT_SCALE {}
      AIPARAM C4DAIP_OBQ_TOONSIMPLE_HIGHLIGHT_EXPONENT {}
      AIPARAM C4DAIP_OBQ_TOONSIMPLE_HIGHLIGHT_COVERAGE {}
      AIPARAM C4DAIP_OBQ_TOONSIMPLE_HIGHLIGHT_SOFTNESS {}
      AIPARAM C4DAIP_OBQ_TOONSIMPLE_RIMLIGHT_COLOR {}
      AIPARAM C4DAIP_OBQ_TOONSIMPLE_RIMLIGHT_SCALE {}
      AIPARAM C4DAIP_OBQ_TOONSIMPLE_RIMLIGHT_COVERAGE {}
      AIPARAM C4DAIP_OBQ_TOONSIMPLE_RIMLIGHT_SOFTNESS {}
      AIPARAM C4DAIP_OBQ_TOONSIMPLE_AMBIENT_FB_STR {}
      AIPARAM C4DAIP_OBQ_TOONSIMPLE_DIFFUSE_FB_STR {}
      AIPARAM C4DAIP_OBQ_TOONSIMPLE_HIGHLIGHT_FB_STR {}
      AIPARAM C4DAIP_OBQ_TOONSIMPLE_RIMLIGHT_FB_STR {}
      AIPARAM C4DAIP_OBQ_TOONSIMPLE_CONTOUR_FB_STR {}
      AIPARAM C4DAIP_OBQ_TOONSIMPLE_PUTALPHAINFB {}
      AIPARAM C4DAIP_OBQ_TOONSIMPLE_OPACITY {}
      AIPARAM C4DAIP_OBQ_TOONSIMPLE_NORMALIZEOBJECTID {}
      AIPARAM C4DAIP_OBQ_TOONSIMPLE_AMBIENT_NOINTERNAL {}
      AIPARAM C4DAIP_OBQ_TOONSIMPLE_DIFFUSE_NOINTERNAL {}
      AIPARAM C4DAIP_OBQ_TOONSIMPLE_HIGHLIGHT_NOINTERNAL {}
      AIPARAM C4DAIP_OBQ_TOONSIMPLE_RIMLIGHT_NOINTERNAL {}
      AIPARAM C4DAIP_OBQ_TOONSIMPLE_GLOBAL_CLAMP {}
   }
}

