CONTAINER AINODE_OBQ_IESLIGHTFILTER
{
   NAME ainode_Obq_IESLightFilter;

   INCLUDE GVbase;

   GROUP C4DAI_OBQ_IESLIGHTFILTER_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_IESLIGHTFILTER_FILENAME {}
   }
}

