CONTAINER AINODE_OBQ_LENSDISTORTION
{
   NAME ainode_Obq_LensDistortion;

   INCLUDE Obase;

   GROUP C4DAI_OBQ_LENSDISTORTION_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_LENSDISTORTION_USEDOF {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_FOCUSDISTANCE {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_APERTURESIZE {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_APERTUREASPECTRATIO {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_USEPOLYGONALAPERTURE {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_APERTUREBLADES {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_APERTUREBLADECURVATURE {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_APERTUREROTATION {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_FOCUSPLANEISPLANE {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_BOKEHINVERT {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_BOKEHBIAS {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_BOKEHGAIN {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_DISTORTIONMODEL {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_K1 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_K2 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_CENTERX {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_CENTERY {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANAMORPHICSQUEEZE {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ASYMMETRICDISTORTIONX {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ASYMMETRICDISTORTIONY {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_CENTERX3DEQ {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_CENTERY3DEQ {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_FILMBACKX3DEQ {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_FILMBACKY3DEQ {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_PIXELRATIO3DEQ {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_C3DC00 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_C3DC01 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_C3DC02 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_C3DC03 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_C3DC04 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA6C00 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA6C01 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA6C02 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA6C03 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA6C04 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA6C05 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA6C06 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA6C07 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA6C08 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA6C09 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA6C10 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA6C11 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA6C12 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA6C13 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA6C14 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA6C15 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA6C16 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA6C17 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_FISH8C00 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_FISH8C01 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_FISH8C02 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_FISH8C03 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_STAND4C00 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_STAND4C01 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_STAND4C02 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_STAND4C03 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_STAND4C04 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_STAND4C05 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_RADDEC4C00 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_RADDEC4C01 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_RADDEC4C02 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_RADDEC4C03 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_RADDEC4C04 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_RADDEC4C05 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_RADDEC4C06 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_RADDEC4C07 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA4C00 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA4C01 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA4C02 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA4C03 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA4C04 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA4C05 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA4C06 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA4C07 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA4C08 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA4C09 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA4C10 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA4C11 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA4C12 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_FOCAL3DEQ {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_FOCUSDISTANCE3DEQ {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_PFC3 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_PFC5 {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_PFSQUEEZE {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_PFXP {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_PFYP {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_FOV {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_POSITION {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_LOOK_AT {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_UP {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_MATRIX {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_NEAR_CLIP {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_FAR_CLIP {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_SHUTTER_START {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_SHUTTER_END {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_SHUTTER_TYPE {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_SHUTTER_CURVE {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ROLLING_SHUTTER {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ROLLING_SHUTTER_DURATION {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_FILTERMAP {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_HANDEDNESS {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_TIME_SAMPLES {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_SCREEN_WINDOW_MIN {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_SCREEN_WINDOW_MAX {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_EXPOSURE {}
   }
}

