CONTAINER AINODE_OBQ_MESSAGEGETVECTOR
{
   NAME ainode_Obq_MessageGetVector;

   INCLUDE GVbase;

   GROUP C4DAI_OBQ_MESSAGEGETVECTOR_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_MESSAGEGETVECTOR_KEY {}
      AIPARAM C4DAIP_OBQ_MESSAGEGETVECTOR_DEFAULTVALUE {}
   }
}

