CONTAINER AINODE_OBQ_NODEINFO
{
   NAME ainode_Obq_NodeInfo;

   INCLUDE GVbase;

   GROUP C4DAI_OBQ_NODEINFO_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_NODEINFO_PASSTHROUGH {}
      AIPARAM C4DAIP_OBQ_NODEINFO_MODE {}
      AIPARAM C4DAIP_OBQ_NODEINFO_NODE_NAME {}
   }
}

