CONTAINER AINODE_OBQ_MESSAGEGETINT
{
   NAME ainode_Obq_MessageGetInt;

   INCLUDE GVbase;

   GROUP C4DAI_OBQ_MESSAGEGETINT_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_MESSAGEGETINT_KEY {}
      AIPARAM C4DAIP_OBQ_MESSAGEGETINT_DEFAULTVALUE {}
   }
}

