CONTAINER AINODE_OBQ_SETALPHA
{
   NAME ainode_Obq_SetAlpha;

   INCLUDE GVbase;

   GROUP C4DAI_OBQ_SETALPHA_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_SETALPHA_COLOR {}
      AIPARAM C4DAIP_OBQ_SETALPHA_ALPHA {}
   }
}

