CONTAINER AINODE_OBQ_SPECTRUMCOLOR
{
   NAME ainode_Obq_SpectrumColor;

   INCLUDE GVbase;

   GROUP C4DAI_OBQ_SPECTRUMCOLOR_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_SPECTRUMCOLOR_MODE {}
      AIPARAM C4DAIP_OBQ_SPECTRUMCOLOR_FILENAME {}
      AIPARAM C4DAIP_OBQ_SPECTRUMCOLOR_LAMBDAUNITS {}
      AIPARAM C4DAIP_OBQ_SPECTRUMCOLOR_LAMBDASSTR {}
      AIPARAM C4DAIP_OBQ_SPECTRUMCOLOR_INTENSITIESSTR {}
      AIPARAM C4DAIP_OBQ_SPECTRUMCOLOR_XYZ2RGB {}
      AIPARAM C4DAIP_OBQ_SPECTRUMCOLOR_GAMMA {}
   }
}

