CONTAINER AINODE_OBQ_STEREOLENS
{
   NAME ainode_Obq_StereoLens;

   INCLUDE Obase;

   GROUP C4DAI_OBQ_STEREOLENS_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_STEREOLENS_VIEWMODE {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_LEFTCAMERA {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_RIGHTCAMERA {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_FILMBACKX {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_LEFTCENTEROFFSET {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_RIGHTCENTEROFFSET {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_RECALCULATEDISTANCEFORSIDECAMERAS {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_TOTALOVERSCANPIXELS {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_USEDOF {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_FOCUSDISTANCE {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_APERTURESIZE {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_APERTUREASPECTRATIO {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_USEPOLYGONALAPERTURE {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_APERTUREBLADES {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_APERTUREBLADECURVATURE {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_APERTUREROTATION {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_FOCUSPLANEISPLANE {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_BOKEHINVERT {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_BOKEHBIAS {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_BOKEHGAIN {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_FOV {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_POSITION {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_LOOK_AT {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_UP {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_MATRIX {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_NEAR_CLIP {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_FAR_CLIP {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_SHUTTER_START {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_SHUTTER_END {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_SHUTTER_TYPE {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_SHUTTER_CURVE {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_ROLLING_SHUTTER {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_ROLLING_SHUTTER_DURATION {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_FILTERMAP {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_HANDEDNESS {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_TIME_SAMPLES {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_SCREEN_WINDOW_MIN {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_SCREEN_WINDOW_MAX {}
      AIPARAM C4DAIP_OBQ_STEREOLENS_EXPOSURE {}
   }
}

