CONTAINER AINODE_OBQ_STEREOLENS
{
	NAME ainode_Obq_StereoLens;

	INCLUDE GVbase;

	GROUP C4DAI_OBQ_STEREOLENS_MAIN_GRP
	{
		DEFAULT 1;

		AIPARAM C4DAIP_OBQ_STEREOLENS_VIEWMODE {}
		AIPARAM C4DAIP_OBQ_STEREOLENS_LEFTCAMERA {}
		AIPARAM C4DAIP_OBQ_STEREOLENS_RIGHTCAMERA {}
		AIPARAM C4DAIP_OBQ_STEREOLENS_FILMBACKX {}
		AIPARAM C4DAIP_OBQ_STEREOLENS_LEFTCENTEROFFSET {}
		AIPARAM C4DAIP_OBQ_STEREOLENS_RIGHTCENTEROFFSET {}
		AIPARAM C4DAIP_OBQ_STEREOLENS_RECALCULATEDISTANCEFORSIDECAM {}
		AIPARAM C4DAIP_OBQ_STEREOLENS_TOTALOVERSCANPIXELS {}
		AIPARAM C4DAIP_OBQ_STEREOLENS_USEDOF {}
		AIPARAM C4DAIP_OBQ_STEREOLENS_FOCUSDISTANCE {}
		AIPARAM C4DAIP_OBQ_STEREOLENS_APERTURESIZE {}
		AIPARAM C4DAIP_OBQ_STEREOLENS_APERTUREASPECTRATIO {}
		AIPARAM C4DAIP_OBQ_STEREOLENS_USEPOLYGONALAPERTURE {}
		AIPARAM C4DAIP_OBQ_STEREOLENS_APERTUREBLADES {}
		AIPARAM C4DAIP_OBQ_STEREOLENS_APERTUREBLADECURVATURE {}
		AIPARAM C4DAIP_OBQ_STEREOLENS_APERTUREROTATION {}
		AIPARAM C4DAIP_OBQ_STEREOLENS_FOCUSPLANEISPLANE {}
		AIPARAM C4DAIP_OBQ_STEREOLENS_BOKEHINVERT {}
		AIPARAM C4DAIP_OBQ_STEREOLENS_BOKEHBIAS {}
		AIPARAM C4DAIP_OBQ_STEREOLENS_BOKEHGAIN {}
	}
}

