CONTAINER AINODE_OBQ_MESSAGEGETBOOL
{
   NAME ainode_Obq_MessageGetBool;

   INCLUDE GVbase;

   GROUP C4DAI_OBQ_MESSAGEGETBOOL_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_MESSAGEGETBOOL_KEY {}
      AIPARAM C4DAIP_OBQ_MESSAGEGETBOOL_DEFAULTVALUE {}
   }
}

