CONTAINER AINODE_OBQ_OPACITY
{
   NAME ainode_Obq_Opacity;

   INCLUDE GVbase;

   GROUP C4DAI_OBQ_OPACITY_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_OPACITY_COLOR {}
      AIPARAM C4DAIP_OBQ_OPACITY_CHANNEL {}
      AIPARAM C4DAIP_OBQ_OPACITY_OPACITYRGBA {}
      AIPARAM C4DAIP_OBQ_OPACITY_OPACITYSCALAR {}
      AIPARAM C4DAIP_OBQ_OPACITY_HARD {}
      AIPARAM C4DAIP_OBQ_OPACITY_THRESHOLD {}
      AIPARAM C4DAIP_OBQ_OPACITY_INVERT {}
   }
}

