CONTAINER AINODE_OBQ_RGBCOMLIGHTFILTER
{
   NAME ainode_Obq_RGBComLightFilter;

   INCLUDE GVbase;

   GROUP C4DAI_OBQ_RGBCOMLIGHTFILTER_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_RGBCOMLIGHTFILTER_DEFAULTCOLOR {}
      AIPARAM C4DAIP_OBQ_RGBCOMLIGHTFILTER_CHANNEL {}
   }
}

