CONTAINER AINODE_OBQ_CAMERAPROJECTIONSPACE
{
   NAME ainode_Obq_CameraProjectionSpace;

   INCLUDE GVbase;

   GROUP C4DAI_OBQ_CAMERAPROJECTIONSPACE_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_CAMERAPROJECTIONSPACE_USE_RENDER_CAMERA {}
      AIPARAM C4DAIP_OBQ_CAMERAPROJECTIONSPACE_PROJECTION_CAMERA {}
      AIPARAM C4DAIP_OBQ_CAMERAPROJECTIONSPACE_CAMERA_ASPECT_RATIO {}
   }
}

