CONTAINER AINODE_OBQ_RGBCOMEMIT
{
   NAME ainode_Obq_RGBComEmit;

   INCLUDE GVbase;

   GROUP C4DAI_OBQ_RGBCOMEMIT_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_RGBCOMEMIT_PASSTHROUGH {}
   }
}

