CONTAINER AINODE_OBQ_ETCHING
{
   NAME ainode_Obq_Etching;

   INCLUDE GVbase;

   GROUP C4DAI_OBQ_ETCHING_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_ETCHING_SHADING_INPUT {}
      AIPARAM C4DAIP_OBQ_ETCHING_COORDINATES_INPUT {}
      AIPARAM C4DAIP_OBQ_ETCHING_USE_LINEAR_SIGNAL {}
      AIPARAM C4DAIP_OBQ_ETCHING_BRIGHT_COLOR {}
      AIPARAM C4DAIP_OBQ_ETCHING_BRIGHT_POINT {}
      AIPARAM C4DAIP_OBQ_ETCHING_DARK_COLOR {}
      AIPARAM C4DAIP_OBQ_ETCHING_DARK_POINT {}
      AIPARAM C4DAIP_OBQ_ETCHING_FREQUENCY {}
      AIPARAM C4DAIP_OBQ_ETCHING_OFFSET {}
      AIPARAM C4DAIP_OBQ_ETCHING_FEATHER {}
      AIPARAM C4DAIP_OBQ_ETCHING_USE_AVERAGE_RGB {}
      AIPARAM C4DAIP_OBQ_ETCHING_MULTIPLY_BRIGHT_COLOR {}
      AIPARAM C4DAIP_OBQ_ETCHING_MULTIPLY_DARK_COLOR {}
      AIPARAM C4DAIP_OBQ_ETCHING_NORMALIZED_BLACK_COLOR {}
      AIPARAM C4DAIP_OBQ_ETCHING_MIX {}
      AIPARAM C4DAIP_OBQ_ETCHING_ENABLE_DOTS {}
      AIPARAM C4DAIP_OBQ_ETCHING_BRIGHT_DOTS_START {}
      AIPARAM C4DAIP_OBQ_ETCHING_DARK_DOTS_START {}
      AIPARAM C4DAIP_OBQ_ETCHING_PROGRESSIVE_DOTS {}
      AIPARAM C4DAIP_OBQ_ETCHING_AOV_MATTE {}
      AIPARAM C4DAIP_OBQ_ETCHING_AOV_INPUT {}
      AIPARAM C4DAIP_OBQ_ETCHING_AUTOFILTERING {}
      AIPARAM C4DAIP_OBQ_ETCHING_AUTOFILTERINGBIAS {}
      AIPARAM C4DAIP_OBQ_ETCHING_AUTOFILTERINGGAIN {}
      AIPARAM C4DAIP_OBQ_ETCHING_AUTOFILTERINGSTART {}
      AIPARAM C4DAIP_OBQ_ETCHING_AUTOFILTERINGEND {}
      AIPARAM C4DAIP_OBQ_ETCHING_AUTOFILTERINGOUT {}
      AIPARAM C4DAIP_OBQ_ETCHING_AUTOFILTERINGU {}
      AIPARAM C4DAIP_OBQ_ETCHING_AUTOFILTERINGMODE {}
      AIPARAM C4DAIP_OBQ_ETCHING_AUTOFILTERINGAUTORANGE {}
   }
}

