CONTAINER AINODE_OBQ_ANGULARCAMERA
{
   NAME ainode_Obq_AngularCamera;

   INCLUDE Obase;

   GROUP C4DAI_OBQ_ANGULARCAMERA_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_ANGULARCAMERA_ANGLE {}
      AIPARAM C4DAIP_OBQ_ANGULARCAMERA_FLIP {}
      AIPARAM C4DAIP_OBQ_ANGULARCAMERA_OVERRENDER {}
      AIPARAM C4DAIP_OBQ_ANGULARCAMERA_POSITION {}
      AIPARAM C4DAIP_OBQ_ANGULARCAMERA_LOOK_AT {}
      AIPARAM C4DAIP_OBQ_ANGULARCAMERA_UP {}
      AIPARAM C4DAIP_OBQ_ANGULARCAMERA_MATRIX {}
      AIPARAM C4DAIP_OBQ_ANGULARCAMERA_NEAR_CLIP {}
      AIPARAM C4DAIP_OBQ_ANGULARCAMERA_FAR_CLIP {}
      AIPARAM C4DAIP_OBQ_ANGULARCAMERA_SHUTTER_START {}
      AIPARAM C4DAIP_OBQ_ANGULARCAMERA_SHUTTER_END {}
      AIPARAM C4DAIP_OBQ_ANGULARCAMERA_SHUTTER_TYPE {}
      AIPARAM C4DAIP_OBQ_ANGULARCAMERA_SHUTTER_CURVE {}
      AIPARAM C4DAIP_OBQ_ANGULARCAMERA_ROLLING_SHUTTER {}
      AIPARAM C4DAIP_OBQ_ANGULARCAMERA_ROLLING_SHUTTER_DURATION {}
      AIPARAM C4DAIP_OBQ_ANGULARCAMERA_FILTERMAP {}
      AIPARAM C4DAIP_OBQ_ANGULARCAMERA_HANDEDNESS {}
      AIPARAM C4DAIP_OBQ_ANGULARCAMERA_TIME_SAMPLES {}
      AIPARAM C4DAIP_OBQ_ANGULARCAMERA_SCREEN_WINDOW_MIN {}
      AIPARAM C4DAIP_OBQ_ANGULARCAMERA_SCREEN_WINDOW_MAX {}
      AIPARAM C4DAIP_OBQ_ANGULARCAMERA_EXPOSURE {}
   }
}

