CONTAINER AINODE_OBQ_FRESNEL
{
   NAME ainode_Obq_Fresnel;

   INCLUDE GVbase;

   GROUP C4DAI_OBQ_FRESNEL_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_FRESNEL_MODE {}
      AIPARAM C4DAIP_OBQ_FRESNEL_IORFILENAME {}
      AIPARAM C4DAIP_OBQ_FRESNEL_LAMBDAUNITS {}
      AIPARAM C4DAIP_OBQ_FRESNEL_IORRGB {}
      AIPARAM C4DAIP_OBQ_FRESNEL_KRGB {}
      AIPARAM C4DAIP_OBQ_FRESNEL_METHOD {}
      AIPARAM C4DAIP_OBQ_FRESNEL_IORINRGB {}
      AIPARAM C4DAIP_OBQ_FRESNEL_RATIOFSFP {}
      AIPARAM C4DAIP_OBQ_FRESNEL_TRANSMITTANCE {}
      AIPARAM C4DAIP_OBQ_FRESNEL_BACKFACEMODE {}
      AIPARAM C4DAIP_OBQ_FRESNEL_USELUT {}
      AIPARAM C4DAIP_OBQ_FRESNEL_LUTSAMPLESIZE {}
      AIPARAM C4DAIP_OBQ_FRESNEL_USEFULLSPECTRUM {}
      AIPARAM C4DAIP_OBQ_FRESNEL_DEGAMMA {}
      AIPARAM C4DAIP_OBQ_FRESNEL_OUTPUTGAMMA {}
      AIPARAM C4DAIP_OBQ_FRESNEL_LAMBDASSTR {}
      AIPARAM C4DAIP_OBQ_FRESNEL_ETASSTR {}
      AIPARAM C4DAIP_OBQ_FRESNEL_KSSTR {}
      AIPARAM C4DAIP_OBQ_FRESNEL_INPUTTYPE {}
      AIPARAM C4DAIP_OBQ_FRESNEL_CCMODE {}
      AIPARAM C4DAIP_OBQ_FRESNEL_HUESHIFT {}
      AIPARAM C4DAIP_OBQ_FRESNEL_SATURATIONMOD {}
      AIPARAM C4DAIP_OBQ_FRESNEL_SATURATIONOP {}
      AIPARAM C4DAIP_OBQ_FRESNEL_ROUGHNESS {}
      AIPARAM C4DAIP_OBQ_FRESNEL_ROUGHNESSSAMPLESIZE {}
      AIPARAM C4DAIP_OBQ_FRESNEL_XYZ2RGB {}
   }
}

