CONTAINER AINODE_OBQ_TOON
{
   NAME ainode_Obq_Toon;

   INCLUDE GVbase;

   GROUP C4DAI_OBQ_TOON_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_TOON_GLOBAL_LOOPLIGHTMODE {}
      AIPARAM C4DAIP_OBQ_TOON_GLOBAL_COMPMODE {}
      AIPARAM C4DAIP_OBQ_TOON_GLOBAL_LOOPMODE {}
      AIPARAM C4DAIP_OBQ_TOON_GLOBAL_MULTBYLIGHTCOLOR {}
      AIPARAM C4DAIP_OBQ_TOON_AMBIENT_COLOR {}
      AIPARAM C4DAIP_OBQ_TOON_AMBIENT_SCALE {}
      AIPARAM C4DAIP_OBQ_TOON_AMBIENT_MULTAMBIENCE {}
      AIPARAM C4DAIP_OBQ_TOON_DIFFUSE_COLOR {}
      AIPARAM C4DAIP_OBQ_TOON_DIFFUSE_SCALE {}
      AIPARAM C4DAIP_OBQ_TOON_DIFFUSE_COVERAGE {}
      AIPARAM C4DAIP_OBQ_TOON_DIFFUSE_SOFTNESS {}
      AIPARAM C4DAIP_OBQ_TOON_DIFFUSE_MODE {}
      AIPARAM C4DAIP_OBQ_TOON_DIFFUSE_GRADIENT {}
      AIPARAM C4DAIP_OBQ_TOON_DIFFUSE_IMAGE {}
      AIPARAM C4DAIP_OBQ_TOON_DIFFUSE_IMAGETYPE {}
      AIPARAM C4DAIP_OBQ_TOON_HIGHLIGHT_COLOR {}
      AIPARAM C4DAIP_OBQ_TOON_HIGHLIGHT_SCALE {}
      AIPARAM C4DAIP_OBQ_TOON_HIGHLIGHT_EXPONENT {}
      AIPARAM C4DAIP_OBQ_TOON_HIGHLIGHT_COVERAGE {}
      AIPARAM C4DAIP_OBQ_TOON_HIGHLIGHT_SOFTNESS {}
      AIPARAM C4DAIP_OBQ_TOON_HIGHLIGHT_MODE {}
      AIPARAM C4DAIP_OBQ_TOON_HIGHLIGHT_GRADIENT {}
      AIPARAM C4DAIP_OBQ_TOON_HIGHLIGHT_IMAGE {}
      AIPARAM C4DAIP_OBQ_TOON_HIGHLIGHT_IMAGETYPE {}
      AIPARAM C4DAIP_OBQ_TOON_RIMLIGHT_COLOR {}
      AIPARAM C4DAIP_OBQ_TOON_RIMLIGHT_SCALE {}
      AIPARAM C4DAIP_OBQ_TOON_RIMLIGHT_COVERAGE {}
      AIPARAM C4DAIP_OBQ_TOON_RIMLIGHT_SOFTNESS {}
      AIPARAM C4DAIP_OBQ_TOON_RIMLIGHT_MODE {}
      AIPARAM C4DAIP_OBQ_TOON_RIMLIGHT_GRADIENT {}
      AIPARAM C4DAIP_OBQ_TOON_RIMLIGHT_IMAGE {}
      AIPARAM C4DAIP_OBQ_TOON_RIMLIGHT_IMAGETYPE {}
      AIPARAM C4DAIP_OBQ_TOON_AMBIENT_FB_STR {}
      AIPARAM C4DAIP_OBQ_TOON_DIFFUSE_FB_STR {}
      AIPARAM C4DAIP_OBQ_TOON_HIGHLIGHT_FB_STR {}
      AIPARAM C4DAIP_OBQ_TOON_RIMLIGHT_FB_STR {}
      AIPARAM C4DAIP_OBQ_TOON_CONTOUR_FB_STR {}
      AIPARAM C4DAIP_OBQ_TOON_PUTALPHAINFB {}
      AIPARAM C4DAIP_OBQ_TOON_DIFFUSE_AUTOREMAP {}
      AIPARAM C4DAIP_OBQ_TOON_DIFFUSE_IMAGEREMAPLEFT {}
      AIPARAM C4DAIP_OBQ_TOON_DIFFUSE_IMAGEREMAPRIGHT {}
      AIPARAM C4DAIP_OBQ_TOON_HIGHLIGHT_AUTOREMAP {}
      AIPARAM C4DAIP_OBQ_TOON_HIGHLIGHT_IMAGEREMAPLEFT {}
      AIPARAM C4DAIP_OBQ_TOON_HIGHLIGHT_IMAGEREMAPRIGHT {}
      AIPARAM C4DAIP_OBQ_TOON_RIMLIGHT_AUTOREMAP {}
      AIPARAM C4DAIP_OBQ_TOON_RIMLIGHT_IMAGEREMAPLEFT {}
      AIPARAM C4DAIP_OBQ_TOON_RIMLIGHT_IMAGEREMAPRIGHT {}
      AIPARAM C4DAIP_OBQ_TOON_DIFFUSE_IMAGEREMAPBIAS {}
      AIPARAM C4DAIP_OBQ_TOON_DIFFUSE_IMAGEREMAPGAIN {}
      AIPARAM C4DAIP_OBQ_TOON_HIGHLIGHT_IMAGEREMAPBIAS {}
      AIPARAM C4DAIP_OBQ_TOON_HIGHLIGHT_IMAGEREMAPGAIN {}
      AIPARAM C4DAIP_OBQ_TOON_RIMLIGHT_IMAGEREMAPBIAS {}
      AIPARAM C4DAIP_OBQ_TOON_RIMLIGHT_IMAGEREMAPGAIN {}
      AIPARAM C4DAIP_OBQ_TOON_OUTPUT_IMAGEONUV {}
      AIPARAM C4DAIP_OBQ_TOON_OPACITY {}
      AIPARAM C4DAIP_OBQ_TOON_NORMALIZEOBJECTID {}
      AIPARAM C4DAIP_OBQ_TOON_AMBIENT_NOINTERNAL {}
      AIPARAM C4DAIP_OBQ_TOON_DIFFUSE_NOINTERNAL {}
      AIPARAM C4DAIP_OBQ_TOON_HIGHLIGHT_NOINTERNAL {}
      AIPARAM C4DAIP_OBQ_TOON_RIMLIGHT_NOINTERNAL {}
      AIPARAM C4DAIP_OBQ_TOON_DIFFUSE_LINEARDOT {}
      AIPARAM C4DAIP_OBQ_TOON_HIGHLIGHT_LINEARDOT {}
      AIPARAM C4DAIP_OBQ_TOON_RIMLIGHT_LINEARDOT {}
      AIPARAM C4DAIP_OBQ_TOON_DIFFUSE_SHADERINPUT {}
      AIPARAM C4DAIP_OBQ_TOON_HIGHLIGHT_SHADERINPUT {}
      AIPARAM C4DAIP_OBQ_TOON_GLOBAL_REMAPMODE {}
      AIPARAM C4DAIP_OBQ_TOON_GLOBAL_REMAPMULTBYCOLOR {}
      AIPARAM C4DAIP_OBQ_TOON_GLOBAL_CLAMP {}
   }
}

