CONTAINER AINODE_OBQ_ROOT2TIP
{
   NAME ainode_Obq_Root2Tip;

   INCLUDE GVbase;

   GROUP C4DAI_OBQ_ROOT2TIP_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_ROOT2TIP_ROOT {}
      AIPARAM C4DAIP_OBQ_ROOT2TIP_TIP {}
      AIPARAM C4DAIP_OBQ_ROOT2TIP_MODE {}
   }
}

