CONTAINER AINODE_OBQ_MESSAGEGETCOLOR
{
   NAME ainode_Obq_MessageGetColor;

   INCLUDE GVbase;

   GROUP C4DAI_OBQ_MESSAGEGETCOLOR_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_MESSAGEGETCOLOR_KEY {}
      AIPARAM C4DAIP_OBQ_MESSAGEGETCOLOR_DEFAULTVALUE {}
   }
}

