CONTAINER AINODE_OBQ_TRANSFORMUV
{
   NAME ainode_Obq_TransformUV;

   INCLUDE GVbase;

   GROUP C4DAI_OBQ_TRANSFORMUV_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_TRANSFORMUV_TEX {}
      AIPARAM C4DAIP_OBQ_TRANSFORMUV_MODE {}
      AIPARAM C4DAIP_OBQ_TRANSFORMUV_SCALEX {}
      AIPARAM C4DAIP_OBQ_TRANSFORMUV_SCALEY {}
      AIPARAM C4DAIP_OBQ_TRANSFORMUV_ROTATE {}
      AIPARAM C4DAIP_OBQ_TRANSFORMUV_TRANSLATEX {}
      AIPARAM C4DAIP_OBQ_TRANSFORMUV_TRANSLATEY {}
      AIPARAM C4DAIP_OBQ_TRANSFORMUV_PIVOTX {}
      AIPARAM C4DAIP_OBQ_TRANSFORMUV_PIVOTY {}
   }
}

