CONTAINER AINODE_OBQ_ATMOSPHERE
{
   NAME ainode_Obq_Atmosphere;

   INCLUDE GVbase;

   GROUP C4DAI_OBQ_ATMOSPHERE_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_ATMOSPHERE_COLORKD {}
      AIPARAM C4DAIP_OBQ_ATMOSPHERE_USE3DKD {}
      AIPARAM C4DAIP_OBQ_ATMOSPHERE_ABSORPTION {}
      AIPARAM C4DAIP_OBQ_ATMOSPHERE_USE3DABSORPTION {}
      AIPARAM C4DAIP_OBQ_ATMOSPHERE_ASYMMETRY {}
      AIPARAM C4DAIP_OBQ_ATMOSPHERE_STEPSIZE {}
      AIPARAM C4DAIP_OBQ_ATMOSPHERE_STEPJITTER {}
      AIPARAM C4DAIP_OBQ_ATMOSPHERE_USEBIASGAIN {}
      AIPARAM C4DAIP_OBQ_ATMOSPHERE_BIAS {}
      AIPARAM C4DAIP_OBQ_ATMOSPHERE_GAIN {}
      AIPARAM C4DAIP_OBQ_ATMOSPHERE_USEBIASGAINDOT {}
      AIPARAM C4DAIP_OBQ_ATMOSPHERE_BIASDOT {}
      AIPARAM C4DAIP_OBQ_ATMOSPHERE_GAINDOT {}
      AIPARAM C4DAIP_OBQ_ATMOSPHERE_RADIUSFALLOFFMODE {}
      AIPARAM C4DAIP_OBQ_ATMOSPHERE_FALLOFFSTART {}
      AIPARAM C4DAIP_OBQ_ATMOSPHERE_FALLOFFEXPONENT {}
      AIPARAM C4DAIP_OBQ_ATMOSPHERE_OBJECTCENTER {}
      AIPARAM C4DAIP_OBQ_ATMOSPHERE_COMPENSATEFORCLOUDOPACITY {}
      AIPARAM C4DAIP_OBQ_ATMOSPHERE_DIVIDECOLORBYOPACITY {}
      AIPARAM C4DAIP_OBQ_ATMOSPHERE_USEMAXIMUMRAYLENGTH {}
      AIPARAM C4DAIP_OBQ_ATMOSPHERE_MAXIMUMRAYLENGTH {}
      AIPARAM C4DAIP_OBQ_ATMOSPHERE_SECONDARYTYPESTOO {}
   }
}

