CONTAINER AINODE_OBQ_RANDOMID
{
   NAME ainode_Obq_RandomID;

   INCLUDE GVbase;

   GROUP C4DAI_OBQ_RANDOMID_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_RANDOMID_RANDMAX {}
      AIPARAM C4DAIP_OBQ_RANDOMID_SEED {}
      AIPARAM C4DAIP_OBQ_RANDOMID_STRIPMODELNAME {}
      AIPARAM C4DAIP_OBQ_RANDOMID_STRIPFRAMENUMBER {}
      AIPARAM C4DAIP_OBQ_RANDOMID_STRIPINSTANCEFRAMENUMBER {}
      AIPARAM C4DAIP_OBQ_RANDOMID_STRIPINSTANCEID {}
      AIPARAM C4DAIP_OBQ_RANDOMID_STRIPINSTANCESHAPE {}
   }
}

