CONTAINER AINODE_OBQ_SHADOW
{
   NAME ainode_Obq_Shadow;

   INCLUDE GVbase;

   GROUP C4DAI_OBQ_SHADOW_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_SHADOW_MODE {}
      AIPARAM C4DAIP_OBQ_SHADOW_TRACETYPE {}
      AIPARAM C4DAIP_OBQ_SHADOW_OPACITY {}
      AIPARAM C4DAIP_OBQ_SHADOW_SHADOWSONUNLIT {}
   }
}

