CONTAINER AINODE_OBQ_TRANSFORMSHADINGPOINT
{
   NAME ainode_Obq_TransformShadingPoint;

   INCLUDE GVbase;

   GROUP C4DAI_OBQ_TRANSFORMSHADINGPOINT_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_TRANSFORMSHADINGPOINT_PASSTHROUGH {}
      AIPARAM C4DAIP_OBQ_TRANSFORMSHADINGPOINT_COORDINATES {}
      AIPARAM C4DAIP_OBQ_TRANSFORMSHADINGPOINT_TRANSFORMS {}
      AIPARAM C4DAIP_OBQ_TRANSFORMSHADINGPOINT_SCALE {}
      AIPARAM C4DAIP_OBQ_TRANSFORMSHADINGPOINT_ROTATION {}
      AIPARAM C4DAIP_OBQ_TRANSFORMSHADINGPOINT_TRANSLATION {}
      AIPARAM C4DAIP_OBQ_TRANSFORMSHADINGPOINT_INVERT {}
      AIPARAM C4DAIP_OBQ_TRANSFORMSHADINGPOINT_MODE {}
      AIPARAM C4DAIP_OBQ_TRANSFORMSHADINGPOINT_ROTATIONORDER {}
   }
}

