CONTAINER AINODE_OBQ_MESSAGEGETFLT
{
   NAME ainode_Obq_MessageGetFlt;

   INCLUDE GVbase;

   GROUP C4DAI_OBQ_MESSAGEGETFLT_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_MESSAGEGETFLT_KEY {}
      AIPARAM C4DAIP_OBQ_MESSAGEGETFLT_DEFAULTVALUE {}
   }
}

