CONTAINER AINODE_OBQ_ENVIRONMENT
{
   NAME ainode_Obq_Environment;

   INCLUDE GVbase;

   GROUP C4DAI_OBQ_ENVIRONMENT_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_ENVIRONMENT_TEX {}
      AIPARAM C4DAIP_OBQ_ENVIRONMENT_CONSIDERALPHA {}
      AIPARAM C4DAIP_OBQ_ENVIRONMENT_MAPMODE {}
      AIPARAM C4DAIP_OBQ_ENVIRONMENT_SAMPLELEVEL {}
      AIPARAM C4DAIP_OBQ_ENVIRONMENT_CONEANGLE {}
      AIPARAM C4DAIP_OBQ_ENVIRONMENT_COSLOBEGLOSS {}
      AIPARAM C4DAIP_OBQ_ENVIRONMENT_USESAMPLECOUNT {}
      AIPARAM C4DAIP_OBQ_ENVIRONMENT_SAMPLECOUNT {}
      AIPARAM C4DAIP_OBQ_ENVIRONMENT_SAMPLECOUNTMULTIPLIER {}
      AIPARAM C4DAIP_OBQ_ENVIRONMENT_ONSURFACEMODE {}
      AIPARAM C4DAIP_OBQ_ENVIRONMENT_IOR {}
      AIPARAM C4DAIP_OBQ_ENVIRONMENT_CUSTOMDIRECTION {}
      AIPARAM C4DAIP_OBQ_ENVIRONMENT_INTENSITYCAM {}
      AIPARAM C4DAIP_OBQ_ENVIRONMENT_INTENSITYDIFGI {}
      AIPARAM C4DAIP_OBQ_ENVIRONMENT_INTENSITYRFL {}
      AIPARAM C4DAIP_OBQ_ENVIRONMENT_INTENSITYGLOSSY {}
      AIPARAM C4DAIP_OBQ_ENVIRONMENT_INTENSITYRFR {}
      AIPARAM C4DAIP_OBQ_ENVIRONMENT_GLOBALROTATION {}
      AIPARAM C4DAIP_OBQ_ENVIRONMENT_ROTATION {}
      AIPARAM C4DAIP_OBQ_ENVIRONMENT_FLIPU {}
      AIPARAM C4DAIP_OBQ_ENVIRONMENT_FLIPV {}
      AIPARAM C4DAIP_OBQ_ENVIRONMENT_OPAQUE {}
   }
}

