CONTAINER AINODE_OBQ_THICKNESS
{
   NAME ainode_Obq_Thickness;

   INCLUDE GVbase;

   GROUP C4DAI_OBQ_THICKNESS_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_THICKNESS_SAMPLELEVEL {}
      AIPARAM C4DAIP_OBQ_THICKNESS_CONEANGLE {}
      AIPARAM C4DAIP_OBQ_THICKNESS_USEVDOTNFORMAXANGLE {}
      AIPARAM C4DAIP_OBQ_THICKNESS_COSLOBEGLOSS {}
      AIPARAM C4DAIP_OBQ_THICKNESS_USESAMPLECOUNT {}
      AIPARAM C4DAIP_OBQ_THICKNESS_SAMPLECOUNT {}
      AIPARAM C4DAIP_OBQ_THICKNESS_SAMPLECOUNTMULTIPLIER {}
      AIPARAM C4DAIP_OBQ_THICKNESS_BACKFACE {}
      AIPARAM C4DAIP_OBQ_THICKNESS_INTERSECTOTHERS {}
      AIPARAM C4DAIP_OBQ_THICKNESS_MAXRAYDEPTH {}
      AIPARAM C4DAIP_OBQ_THICKNESS_NORMALIZEMODE {}
      AIPARAM C4DAIP_OBQ_THICKNESS_MAXRAYLENGTH {}
      AIPARAM C4DAIP_OBQ_THICKNESS_USEMAXRAYLENGTH {}
      AIPARAM C4DAIP_OBQ_THICKNESS_DIRMODE {}
      AIPARAM C4DAIP_OBQ_THICKNESS_DIRINVERTED {}
      AIPARAM C4DAIP_OBQ_THICKNESS_DIRSMOOTH {}
      AIPARAM C4DAIP_OBQ_THICKNESS_DIRGEOMETRIC {}
      AIPARAM C4DAIP_OBQ_THICKNESS_DIRSAFE {}
      AIPARAM C4DAIP_OBQ_THICKNESS_CUSTOMDIRECTION {}
      AIPARAM C4DAIP_OBQ_THICKNESS_IOR {}
      AIPARAM C4DAIP_OBQ_THICKNESS_NOHITMODE {}
      AIPARAM C4DAIP_OBQ_THICKNESS_MULTNDOTR {}
      AIPARAM C4DAIP_OBQ_THICKNESS_NDOTREXP {}
      AIPARAM C4DAIP_OBQ_THICKNESS_ENTERSURFACE {}
      AIPARAM C4DAIP_OBQ_THICKNESS_GEOMETRICLIMITMULTIPLIER {}
      AIPARAM C4DAIP_OBQ_THICKNESS_THICKNESSMODE {}
      AIPARAM C4DAIP_OBQ_THICKNESS_MULTIPLYBYDEPTH {}
   }
}

