CONTAINER AINODE_OBQ_CHANGERANGE
{
   NAME ainode_Obq_ChangeRange;

   INCLUDE GVbase;

   GROUP C4DAI_OBQ_CHANGERANGE_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_CHANGERANGE_INPUT {}
      AIPARAM C4DAIP_OBQ_CHANGERANGE_OSTART {}
      AIPARAM C4DAIP_OBQ_CHANGERANGE_OEND {}
      AIPARAM C4DAIP_OBQ_CHANGERANGE_NSTART {}
      AIPARAM C4DAIP_OBQ_CHANGERANGE_NEND {}
      AIPARAM C4DAIP_OBQ_CHANGERANGE_CLAMP {}
      AIPARAM C4DAIP_OBQ_CHANGERANGE_BIAS {}
      AIPARAM C4DAIP_OBQ_CHANGERANGE_GAIN {}
   }
}

