CONTAINER AINODE_OBQ_SURFACEENVIRONMENT
{
   NAME ainode_Obq_SurfaceEnvironment;

   INCLUDE GVbase;

   GROUP C4DAI_OBQ_SURFACEENVIRONMENT_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_SURFACEENVIRONMENT_TEX {}
      AIPARAM C4DAIP_OBQ_SURFACEENVIRONMENT_CONSIDERALPHA {}
      AIPARAM C4DAIP_OBQ_SURFACEENVIRONMENT_MAPMODE {}
      AIPARAM C4DAIP_OBQ_SURFACEENVIRONMENT_USEPASSENVSHADER {}
      AIPARAM C4DAIP_OBQ_SURFACEENVIRONMENT_RAYTYPEENV {}
      AIPARAM C4DAIP_OBQ_SURFACEENVIRONMENT_USEINTENSITYENV {}
      AIPARAM C4DAIP_OBQ_SURFACEENVIRONMENT_USETRANSFORMSENV {}
      AIPARAM C4DAIP_OBQ_SURFACEENVIRONMENT_USEROUGHNESSENV {}
      AIPARAM C4DAIP_OBQ_SURFACEENVIRONMENT_SAMPLELEVEL {}
      AIPARAM C4DAIP_OBQ_SURFACEENVIRONMENT_CONEANGLE {}
      AIPARAM C4DAIP_OBQ_SURFACEENVIRONMENT_COSLOBEGLOSS {}
      AIPARAM C4DAIP_OBQ_SURFACEENVIRONMENT_USESAMPLECOUNT {}
      AIPARAM C4DAIP_OBQ_SURFACEENVIRONMENT_SAMPLECOUNT {}
      AIPARAM C4DAIP_OBQ_SURFACEENVIRONMENT_SAMPLECOUNTMULTIPLIER {}
      AIPARAM C4DAIP_OBQ_SURFACEENVIRONMENT_ONSURFACEMODE {}
      AIPARAM C4DAIP_OBQ_SURFACEENVIRONMENT_IOR {}
      AIPARAM C4DAIP_OBQ_SURFACEENVIRONMENT_CUSTOMDIRECTION {}
      AIPARAM C4DAIP_OBQ_SURFACEENVIRONMENT_INTENSITY {}
      AIPARAM C4DAIP_OBQ_SURFACEENVIRONMENT_GLOBALROTATION {}
      AIPARAM C4DAIP_OBQ_SURFACEENVIRONMENT_ROTATION {}
      AIPARAM C4DAIP_OBQ_SURFACEENVIRONMENT_PASSTHROUGH {}
      AIPARAM C4DAIP_OBQ_SURFACEENVIRONMENT_PASSTHROUGHSHADER {}
      AIPARAM C4DAIP_OBQ_SURFACEENVIRONMENT_RENDERCHANNEL {}
      AIPARAM C4DAIP_OBQ_SURFACEENVIRONMENT_FLIPU {}
      AIPARAM C4DAIP_OBQ_SURFACEENVIRONMENT_FLIPV {}
   }
}

