CONTAINER AINODE_OBQ_HAIR
{
   NAME ainode_Obq_Hair;

   INCLUDE GVbase;

   GROUP C4DAI_OBQ_HAIR_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_HAIR_OPACITY {}
      AIPARAM C4DAIP_OBQ_HAIR_ALPHA_R {}
      AIPARAM C4DAIP_OBQ_HAIR_ALPHA_TT {}
      AIPARAM C4DAIP_OBQ_HAIR_ALPHA_TRT {}
      AIPARAM C4DAIP_OBQ_HAIR_BETA_R {}
      AIPARAM C4DAIP_OBQ_HAIR_BETA_TT {}
      AIPARAM C4DAIP_OBQ_HAIR_BETA_TRT {}
      AIPARAM C4DAIP_OBQ_HAIR_COLOR_R {}
      AIPARAM C4DAIP_OBQ_HAIR_COLOR_TT {}
      AIPARAM C4DAIP_OBQ_HAIR_COLOR_TRT {}
      AIPARAM C4DAIP_OBQ_HAIR_COLOR_G {}
      AIPARAM C4DAIP_OBQ_HAIR_GAMMA_TT {}
      AIPARAM C4DAIP_OBQ_HAIR_GAMMA_G {}
      AIPARAM C4DAIP_OBQ_HAIR_PHI_G {}
      AIPARAM C4DAIP_OBQ_HAIR_SCALE_R {}
      AIPARAM C4DAIP_OBQ_HAIR_SCALE_TT {}
      AIPARAM C4DAIP_OBQ_HAIR_SCALE_TRT {}
      AIPARAM C4DAIP_OBQ_HAIR_SCALE_G {}
      AIPARAM C4DAIP_OBQ_HAIR_ALPHA_R__PRE {}
      AIPARAM C4DAIP_OBQ_HAIR_ALPHA_TT__PRE {}
      AIPARAM C4DAIP_OBQ_HAIR_ALPHA_TRT__PRE {}
      AIPARAM C4DAIP_OBQ_HAIR_BETA_R__PRE {}
      AIPARAM C4DAIP_OBQ_HAIR_BETA_TT__PRE {}
      AIPARAM C4DAIP_OBQ_HAIR_BETA_TRT__PRE {}
      AIPARAM C4DAIP_OBQ_HAIR_COLOR_R__PRE {}
      AIPARAM C4DAIP_OBQ_HAIR_COLOR_TT__PRE {}
      AIPARAM C4DAIP_OBQ_HAIR_COLOR_TRT__PRE {}
      AIPARAM C4DAIP_OBQ_HAIR_COLOR_G__PRE {}
      AIPARAM C4DAIP_OBQ_HAIR_GAMMA_TT__PRE {}
      AIPARAM C4DAIP_OBQ_HAIR_GAMMA_G__PRE {}
      AIPARAM C4DAIP_OBQ_HAIR_PHI_G__PRE {}
      AIPARAM C4DAIP_OBQ_HAIR_SCALE_R__PRE {}
      AIPARAM C4DAIP_OBQ_HAIR_SCALE_TT__PRE {}
      AIPARAM C4DAIP_OBQ_HAIR_SCALE_TRT__PRE {}
      AIPARAM C4DAIP_OBQ_HAIR_SCALE_G__PRE {}
      AIPARAM C4DAIP_OBQ_HAIR_SAMPLES {}
      AIPARAM C4DAIP_OBQ_HAIR_SCALE_DIRECT {}
      AIPARAM C4DAIP_OBQ_HAIR_COLOR_DIRECT {}
      AIPARAM C4DAIP_OBQ_HAIR_SCALE_INDIRECT {}
      AIPARAM C4DAIP_OBQ_HAIR_COLOR_INDIRECT {}
      AIPARAM C4DAIP_OBQ_HAIR_ALPHA_BACK {}
      AIPARAM C4DAIP_OBQ_HAIR_BETA_BACK {}
      AIPARAM C4DAIP_OBQ_HAIR_SCALE_BACK {}
      AIPARAM C4DAIP_OBQ_HAIR_COLOR_BACK {}
      AIPARAM C4DAIP_OBQ_HAIR_SCALE_FORWARD {}
      AIPARAM C4DAIP_OBQ_HAIR_COLOR_FORWARD {}
      AIPARAM C4DAIP_OBQ_HAIR_USE_PRE_ONLY {}
      AIPARAM C4DAIP_OBQ_HAIR_SHADOW_OPACITY {}
      AIPARAM C4DAIP_OBQ_HAIR_NUMGMS_MODIFIER {}
      AIPARAM C4DAIP_OBQ_HAIR_NORMAL_SHIFTS_WIDTHS {}
      AIPARAM C4DAIP_OBQ_HAIR_COLOR_RAY_GLOSSY {}
      AIPARAM C4DAIP_OBQ_HAIR_MODE_RAY_GLOSSY {}
      AIPARAM C4DAIP_OBQ_HAIR_COLOR_RAY_DIFFUSE {}
      AIPARAM C4DAIP_OBQ_HAIR_MODE_RAY_DIFFUSE {}
      AIPARAM C4DAIP_OBQ_HAIR_D_F {}
      AIPARAM C4DAIP_OBQ_HAIR_D_F__PRE {}
      AIPARAM C4DAIP_OBQ_HAIR_D_B {}
      AIPARAM C4DAIP_OBQ_HAIR_D_B__PRE {}
      AIPARAM C4DAIP_OBQ_HAIR_AOV_MODE {}
      AIPARAM C4DAIP_OBQ_HAIR_SINGLESCATTERINGMODE {}
      AIPARAM C4DAIP_OBQ_HAIR_USEIMPORTANCESAMPLING {}
      AIPARAM C4DAIP_OBQ_HAIR_UNLINKOPACITY {}
      AIPARAM C4DAIP_OBQ_HAIR_COLOR_RAY_REFLECTED {}
      AIPARAM C4DAIP_OBQ_HAIR_MODE_RAY_REFLECTED {}
      AIPARAM C4DAIP_OBQ_HAIR_COLOR_RAY_REFRACTED {}
      AIPARAM C4DAIP_OBQ_HAIR_MODE_RAY_REFRACTED {}
      AIPARAM C4DAIP_OBQ_HAIR_CHECKSHADERNAMETOO {}
      AIPARAM C4DAIP_OBQ_HAIR_MODEMIS {}
      AIPARAM C4DAIP_OBQ_HAIR_MISRANDOMLOBESAMPLES {}
      AIPARAM C4DAIP_OBQ_HAIR_SAMPLES_R {}
      AIPARAM C4DAIP_OBQ_HAIR_SAMPLES_TT {}
      AIPARAM C4DAIP_OBQ_HAIR_SAMPLES_TRT {}
      AIPARAM C4DAIP_OBQ_HAIR_SAMPLES_G {}
      AIPARAM C4DAIP_OBQ_HAIR_SAMPLES_DS {}
      AIPARAM C4DAIP_OBQ_HAIR_MODEMIS_DS {}
      AIPARAM C4DAIP_OBQ_HAIR_AOV_DIR_R {}
      AIPARAM C4DAIP_OBQ_HAIR_AOV_DIR_TRT {}
      AIPARAM C4DAIP_OBQ_HAIR_AOV_DIR_G {}
      AIPARAM C4DAIP_OBQ_HAIR_AOV_DIR_TT {}
      AIPARAM C4DAIP_OBQ_HAIR_AOV_DIR_BACK {}
      AIPARAM C4DAIP_OBQ_HAIR_AOV_DIR_SCATTER {}
      AIPARAM C4DAIP_OBQ_HAIR_AOV_DIR_SCATTER_BACK {}
      AIPARAM C4DAIP_OBQ_HAIR_AOV_INDIR_R {}
      AIPARAM C4DAIP_OBQ_HAIR_AOV_INDIR_TRT {}
      AIPARAM C4DAIP_OBQ_HAIR_AOV_INDIR_G {}
      AIPARAM C4DAIP_OBQ_HAIR_AOV_INDIR_TT {}
      AIPARAM C4DAIP_OBQ_HAIR_AOV_INDIR_BACK {}
      AIPARAM C4DAIP_OBQ_HAIR_AOV_INDIR_SCATTER {}
      AIPARAM C4DAIP_OBQ_HAIR_AOV_INDIR_SCATTER_BACK {}
   }
}

