CONTAINER AINODE_OBQ_UVREMAPLENSDISTORTION
{
   NAME ainode_Obq_UVRemapLensDistortion;

   INCLUDE GVbase;

   GROUP C4DAI_OBQ_UVREMAPLENSDISTORTION_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_DISTORTIONMODEL {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_K1 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_K2 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_CENTERX {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_CENTERY {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_ANAMORPHICSQUEEZE {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_ASYMMETRICDISTORTIONX {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_ASYMMETRICDISTORTIONY {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_CENTERX3DEQ {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_CENTERY3DEQ {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_FILMBACKX3DEQ {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_FILMBACKY3DEQ {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_PIXELRATIO3DEQ {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_C3DC00 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_C3DC01 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_C3DC02 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_C3DC03 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_C3DC04 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_ANA6C00 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_ANA6C01 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_ANA6C02 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_ANA6C03 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_ANA6C04 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_ANA6C05 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_ANA6C06 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_ANA6C07 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_ANA6C08 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_ANA6C09 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_ANA6C10 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_ANA6C11 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_ANA6C12 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_ANA6C13 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_ANA6C14 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_ANA6C15 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_ANA6C16 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_ANA6C17 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_FISH8C00 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_FISH8C01 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_FISH8C02 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_FISH8C03 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_STAND4C00 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_STAND4C01 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_STAND4C02 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_STAND4C03 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_STAND4C04 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_STAND4C05 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_RADDEC4C00 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_RADDEC4C01 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_RADDEC4C02 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_RADDEC4C03 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_RADDEC4C04 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_RADDEC4C05 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_RADDEC4C06 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_RADDEC4C07 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_ANA4C00 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_ANA4C01 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_ANA4C02 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_ANA4C03 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_ANA4C04 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_ANA4C05 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_ANA4C06 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_ANA4C07 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_ANA4C08 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_ANA4C09 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_ANA4C10 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_ANA4C11 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_ANA4C12 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_FOCAL3DEQ {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_FOCUSDISTANCE3DEQ {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_PFC3 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_PFC5 {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_PFSQUEEZE {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_PFXP {}
      AIPARAM C4DAIP_OBQ_UVREMAPLENSDISTORTION_PFYP {}
   }
}

