CONTAINER AINODE_OBQ_RANDOMCOLOR
{
   NAME ainode_Obq_RandomColor;

   INCLUDE GVbase;

   GROUP C4DAI_OBQ_RANDOMCOLOR_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_RANDOMCOLOR_RANDMAX {}
      AIPARAM C4DAIP_OBQ_RANDOMCOLOR_SEED {}
      AIPARAM C4DAIP_OBQ_RANDOMCOLOR_COLOR01 {}
      AIPARAM C4DAIP_OBQ_RANDOMCOLOR_COLOR02 {}
      AIPARAM C4DAIP_OBQ_RANDOMCOLOR_COLOR03 {}
      AIPARAM C4DAIP_OBQ_RANDOMCOLOR_COLOR04 {}
      AIPARAM C4DAIP_OBQ_RANDOMCOLOR_COLOR05 {}
      AIPARAM C4DAIP_OBQ_RANDOMCOLOR_COLOR06 {}
      AIPARAM C4DAIP_OBQ_RANDOMCOLOR_COLOR07 {}
      AIPARAM C4DAIP_OBQ_RANDOMCOLOR_COLOR08 {}
      AIPARAM C4DAIP_OBQ_RANDOMCOLOR_COLOR09 {}
      AIPARAM C4DAIP_OBQ_RANDOMCOLOR_COLOR10 {}
      AIPARAM C4DAIP_OBQ_RANDOMCOLOR_COLOR11 {}
      AIPARAM C4DAIP_OBQ_RANDOMCOLOR_COLOR12 {}
      AIPARAM C4DAIP_OBQ_RANDOMCOLOR_COLOR13 {}
      AIPARAM C4DAIP_OBQ_RANDOMCOLOR_COLOR14 {}
      AIPARAM C4DAIP_OBQ_RANDOMCOLOR_COLOR15 {}
      AIPARAM C4DAIP_OBQ_RANDOMCOLOR_COLOR16 {}
      AIPARAM C4DAIP_OBQ_RANDOMCOLOR_STRIPMODELNAME {}
      AIPARAM C4DAIP_OBQ_RANDOMCOLOR_STRIPFRAMENUMBER {}
      AIPARAM C4DAIP_OBQ_RANDOMCOLOR_STRIPINSTANCEFRAMENUMBER {}
      AIPARAM C4DAIP_OBQ_RANDOMCOLOR_STRIPINSTANCEID {}
      AIPARAM C4DAIP_OBQ_RANDOMCOLOR_STRIPINSTANCESHAPE {}
   }
}

