CONTAINER AINODE_OBQ_LIGHTSATURATIONFILTER
{
   NAME ainode_Obq_LightSaturationFilter;

   INCLUDE GVbase;

   GROUP C4DAI_OBQ_LIGHTSATURATIONFILTER_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_LIGHTSATURATIONFILTER_MODE {}
      AIPARAM C4DAIP_OBQ_LIGHTSATURATIONFILTER_KEY {}
      AIPARAM C4DAIP_OBQ_LIGHTSATURATIONFILTER_TRIGGERVALUE {}
      AIPARAM C4DAIP_OBQ_LIGHTSATURATIONFILTER_SATURATION {}
      AIPARAM C4DAIP_OBQ_LIGHTSATURATIONFILTER_DEFAULTSATURATION {}
   }
}

