CONTAINER AINODE_OBQ_VOLUMETHICKNESS
{
   NAME ainode_Obq_VolumeThickness;

   INCLUDE GVbase;

   GROUP C4DAI_OBQ_VOLUMETHICKNESS_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_VOLUMETHICKNESS_COLORIN {}
      AIPARAM C4DAIP_OBQ_VOLUMETHICKNESS_EMISSIONCOLOR {}
      AIPARAM C4DAIP_OBQ_VOLUMETHICKNESS_ALPHAMODE {}
      AIPARAM C4DAIP_OBQ_VOLUMETHICKNESS_ALPHA {}
      AIPARAM C4DAIP_OBQ_VOLUMETHICKNESS_THICKNESSMODE {}
      AIPARAM C4DAIP_OBQ_VOLUMETHICKNESS_THICKNESS {}
      AIPARAM C4DAIP_OBQ_VOLUMETHICKNESS_ACCUMULATEDTHICKNESSTHRESHOLD {}
      AIPARAM C4DAIP_OBQ_VOLUMETHICKNESS_RADIUS {}
      AIPARAM C4DAIP_OBQ_VOLUMETHICKNESS_EXPONENT {}
      AIPARAM C4DAIP_OBQ_VOLUMETHICKNESS_USEABSORPTION {}
      AIPARAM C4DAIP_OBQ_VOLUMETHICKNESS_ABSORPTION {}
      AIPARAM C4DAIP_OBQ_VOLUMETHICKNESS_DIFFUSEMODE {}
      AIPARAM C4DAIP_OBQ_VOLUMETHICKNESS_AUTOTRANSPARENCYMODE {}
      AIPARAM C4DAIP_OBQ_VOLUMETHICKNESS_SHADOWMODIFIER {}
      AIPARAM C4DAIP_OBQ_VOLUMETHICKNESS_LIGHTPROPAGATIONDISTANCE {}
      AIPARAM C4DAIP_OBQ_VOLUMETHICKNESS_DOUBLEHEMISPHERICALDIFFUSE {}
      AIPARAM C4DAIP_OBQ_VOLUMETHICKNESS_LIGHTPROPAGATIONDISTANCEDIFFUSE {}
   }
}

