CONTAINER AINODE_OBQ_COLORSPACECONVERTER
{
   NAME ainode_Obq_ColorspaceConverter;

   INCLUDE GVbase;

   GROUP C4DAI_OBQ_COLORSPACECONVERTER_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_COLORSPACECONVERTER_COLOR {}
      AIPARAM C4DAIP_OBQ_COLORSPACECONVERTER_CSGAMMAIN {}
      AIPARAM C4DAIP_OBQ_COLORSPACECONVERTER_CSGAMMAOUT {}
      AIPARAM C4DAIP_OBQ_COLORSPACECONVERTER_CSILLUMINANTIN {}
      AIPARAM C4DAIP_OBQ_COLORSPACECONVERTER_CSILLUMINANTOUT {}
      AIPARAM C4DAIP_OBQ_COLORSPACECONVERTER_CSPRIMARIESIN {}
      AIPARAM C4DAIP_OBQ_COLORSPACECONVERTER_CSPRIMARIESOUT {}
      AIPARAM C4DAIP_OBQ_COLORSPACECONVERTER_SWITCHINOUT {}
      AIPARAM C4DAIP_OBQ_COLORSPACECONVERTER_USEBRADFORD {}
      AIPARAM C4DAIP_OBQ_COLORSPACECONVERTER_CLAMP {}
   }
}

