CONTAINER AITAG_OBQ_KETTLEUVSTEREOLENS
{
   NAME aitag_Obq_KettleUVStereoLens;

   GROUP C4DAI_OBQ_KETTLEUVSTEREOLENS_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_ORIGIN_POLYMESH {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_ORIGIN_CAMERA {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_TARGET_POLYMESH {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_TARGET_CAMERA {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_GRID_SIZE {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_VIEW_MODE {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_STEREO_TYPE {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_INTERAXIAL_MODE {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_INTERAXIAL_EPSILON {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_INTERAXIAL_SEPARATION {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_ZERO_PARALLAX_MODE {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_ZERO_PARALLAX_DISTANCE {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_TOTAL_OVERSCAN_PIXELS {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_USE_RENDER_REGION {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_REGIONU0 {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_REGIONV0 {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_REGIONU1 {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_REGIONV1 {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_CROP_TO_REGION {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_UV_SET_ORIGIN {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_UV_SET_TARGET {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_USE_DOF {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_APERTURE_SIZE_ {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_APERTURE_ASPECT_RATIO_ {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_USE_POLYGONAL_APERTURE {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_APERTURE_BLADES_ {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_APERTURE_BLADE_CURVATURE_ {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_APERTURE_ROTATION_ {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_BOKEH_INVERT {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_BOKEH_BIAS {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_BOKEH_GAIN {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_POSITION {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_LOOK_AT {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_UP {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_MATRIX {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_NEAR_CLIP {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_FAR_CLIP {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_SHUTTER_START {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_SHUTTER_END {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_SHUTTER_TYPE {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_SHUTTER_CURVE {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_ROLLING_SHUTTER {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_ROLLING_SHUTTER_DURATION {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_FILTERMAP {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_HANDEDNESS {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_TIME_SAMPLES {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_SCREEN_WINDOW_MIN {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_SCREEN_WINDOW_MAX {}
      AIPARAM C4DAIP_OBQ_KETTLEUVSTEREOLENS_EXPOSURE {}
   }
}

