CONTAINER AITAG_OBQ_LENSDISTORTION
{
  NAME aitag_Obq_LensDistortion;

  GROUP C4DAIP_OBQ_LENSDISTORTION_MAIN_ATTRIBUTES_GRP
  {
    DEFAULT 1;

    GROUP C4DAIP_OBQ_LENSDISTORTION_MAIN_GRP
    {
      DEFAULT 1;
      
      GROUP C4DAIP_OBQ_LENSDISTORTION_DISTORTION_MODEL_GRP
      {
        DEFAULT 1;
        
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_DISTORTIONMODEL {}
      }
      
      GROUP C4DAIP_OBQ_LENSDISTORTION_DISTORTION_COEFFICIENTS_GRP
      {
        DEFAULT 1;
        
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_K1 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_K2 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANAMORPHICSQUEEZE {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_ASYMMETRICDISTORTIONX {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_ASYMMETRICDISTORTIONY {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_C3DC00 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_C3DC01 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_C3DC02 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_C3DC03 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_C3DC04 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA6C00 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA6C01 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA6C02 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA6C03 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA6C04 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA6C05 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA6C06 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA6C07 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA6C08 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA6C09 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA6C10 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA6C11 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA6C12 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA6C13 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA6C14 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA6C15 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA6C16 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA6C17 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_FISH8C00 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_FISH8C01 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_FISH8C02 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_FISH8C03 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_STAND4C00 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_STAND4C01 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_STAND4C02 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_STAND4C03 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_STAND4C04 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_STAND4C05 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_RADDEC4C00 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_RADDEC4C01 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_RADDEC4C02 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_RADDEC4C03 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_RADDEC4C04 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_RADDEC4C05 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_RADDEC4C06 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_RADDEC4C07 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA4C00 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA4C01 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA4C02 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA4C03 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA4C04 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA4C05 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA4C06 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA4C07 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA4C08 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA4C09 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA4C10 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA4C11 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_ANA4C12 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_PFC3 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_PFC5 {}
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_PFSQUEEZE {}
      }
      
     
      GROUP C4DAIP_OBQ_LENSDISTORTION_CAMERA_INFO_GRP
      {
        DEFAULT 1;  

        GROUP C4DAIP_OBQ_LENSDISTORTION_FILM_APERTURE_GRP
        {
          DEFAULT 1;  
          
          AIPARAM C4DAIP_OBQ_LENSDISTORTION_FILMBACKX3DEQ {}
          AIPARAM C4DAIP_OBQ_LENSDISTORTION_FILMBACKY3DEQ {}
          AIPARAM C4DAIP_OBQ_LENSDISTORTION_PIXELRATIO3DEQ {}
        }
        
           
        GROUP C4DAIP_OBQ_LENSDISTORTION_CENTER_OFFSET_GRP
        {
          DEFAULT 1;  
          
          AIPARAM C4DAIP_OBQ_LENSDISTORTION_CENTERX {}
          AIPARAM C4DAIP_OBQ_LENSDISTORTION_CENTERY {}
          AIPARAM C4DAIP_OBQ_LENSDISTORTION_CENTERX3DEQ {}
          AIPARAM C4DAIP_OBQ_LENSDISTORTION_CENTERY3DEQ {}
        }
        
        
        GROUP C4DAIP_OBQ_LENSDISTORTION_LENS_CENTER_GRP
        {
          DEFAULT 1;  
          
          AIPARAM C4DAIP_OBQ_LENSDISTORTION_PFXP {}
          AIPARAM C4DAIP_OBQ_LENSDISTORTION_PFYP {}
        }
        
        
        GROUP C4DAIP_OBQ_LENSDISTORTION_FOCAL_GRP
        {
          DEFAULT 1;  
          
          AIPARAM C4DAIP_OBQ_LENSDISTORTION_FOCAL3DEQ {}
          AIPARAM C4DAIP_OBQ_LENSDISTORTION_FOCUSDISTANCE3DEQ {}
        }
      }

       
      GROUP C4DAIP_OBQ_LENSDISTORTION_DEPTH_OF_FIELD_GRP
      {
        DEFAULT 1;  
        
        AIPARAM C4DAIP_OBQ_LENSDISTORTION_USEDOF {}
      
        GROUP C4DAIP_OBQ_LENSDISTORTION_FOCUS_DISTANCE_GRP
        {
          DEFAULT 1; 
          
          AIPARAM C4DAIP_OBQ_LENSDISTORTION_FOCUSDISTANCE {}
          AIPARAM C4DAIP_OBQ_LENSDISTORTION_FOCUSPLANEISPLANE {}
        }
        
        
        GROUP C4DAIP_OBQ_LENSDISTORTION_APERTURE_GRP
        {
          DEFAULT 1; 
          
          AIPARAM C4DAIP_OBQ_LENSDISTORTION_APERTURESIZE {}
          AIPARAM C4DAIP_OBQ_LENSDISTORTION_APERTUREASPECTRATIO {}
          AIPARAM C4DAIP_OBQ_LENSDISTORTION_USEPOLYGONALAPERTURE {}
          AIPARAM C4DAIP_OBQ_LENSDISTORTION_APERTUREBLADES {}
          AIPARAM C4DAIP_OBQ_LENSDISTORTION_APERTUREBLADECURVATURE {}
          AIPARAM C4DAIP_OBQ_LENSDISTORTION_APERTUREROTATION {}
        }
        
        
        GROUP C4DAIP_OBQ_LENSDISTORTION_BOKEH_QUALITY_GRP
        {
          DEFAULT 1; 
          
          AIPARAM C4DAIP_OBQ_LENSDISTORTION_BOKEHINVERT {}
          AIPARAM C4DAIP_OBQ_LENSDISTORTION_BOKEHBIAS {}
          AIPARAM C4DAIP_OBQ_LENSDISTORTION_BOKEHGAIN {} 
        }
        
        
        GROUP C4DAIP_OBQ_LENSDISTORTION_PRESETS_GRP
        {
          DEFAULT 0; 
          
        }
      }
    }
     
    GROUP C4DAIP_OBQ_LENSDISTORTION_OPTIONS_ATTRIBUTES_GRP
    {
      DEFAULT 0;
          
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_EXPOSURE {} 
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_FILTERMAP {}

      SEPARATOR {LINE;}

      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ROLLING_SHUTTER {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_ROLLING_SHUTTER_DURATION {}

      SEPARATOR {LINE;}

      AIPARAM C4DAIP_OBQ_LENSDISTORTION_SHUTTER_START {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_SHUTTER_END {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_SHUTTER_TYPE {}
      AIPARAM C4DAIP_OBQ_LENSDISTORTION_SHUTTER_CURVE {}
    }
  }
}

