CONTAINER AITAG_OBQ_ANGULARCAMERA
{
   NAME aitag_Obq_AngularCamera;

   GROUP C4DAI_OBQ_ANGULARCAMERA_MAIN_GRP
   {
      DEFAULT 1;

      GROUP C4DAIP_OBQ_ANGULARCAMERA_MAIN_ATTRIBUTES_GRP
      {
      DEFAULT 1;
      
      AIPARAM C4DAIP_OBQ_ANGULARCAMERA_ANGLE {}
      AIPARAM C4DAIP_OBQ_ANGULARCAMERA_FLIP {}
      AIPARAM C4DAIP_OBQ_ANGULARCAMERA_OVERRENDER {}
      }

      GROUP C4DAIP_OBQ_ANGULARCAMERA_OPTIONS_ATTRIBUTES_GRP
      {
      DEFAULT 1;
      
      AIPARAM C4DAIP_OBQ_ANGULARCAMERA_EXPOSURE {}
      }
   }
}

