CONTAINER AITAG_OBQ_ANGULARCAMERA
{
  NAME aitag_Obq_AngularCamera;

  GROUP C4DAIP_OBQ_ANGULARCAMERA_MAIN_ATTRIBUTES_GRP
  {
    DEFAULT 1;
    
    GROUP C4DAIP_OBQ_ANGULARCAMERA_MAIN_GRP
    {
    DEFAULT 1;
    
    AIPARAM C4DAIP_OBQ_ANGULARCAMERA_ANGLE {}
    AIPARAM C4DAIP_OBQ_ANGULARCAMERA_FLIP {}
    AIPARAM C4DAIP_OBQ_ANGULARCAMERA_OVERRENDER {}
    }
    
    GROUP C4DAIP_OBQ_ANGULARCAMERA_OPTIONS_ATTRIBUTES_GRP
    {
      DEFAULT 0;
      
      AIPARAM C4DAIP_OBQ_ANGULARCAMERA_EXPOSURE {}
      AIPARAM C4DAIP_OBQ_ANGULARCAMERA_FILTERMAP {}
      
      SEPARATOR {LINE;}
      
      AIPARAM C4DAIP_OBQ_ANGULARCAMERA_ROLLING_SHUTTER {}
      AIPARAM C4DAIP_OBQ_ANGULARCAMERA_ROLLING_SHUTTER_DURATION {}
      
      SEPARATOR {LINE;}
      
      AIPARAM C4DAIP_OBQ_ANGULARCAMERA_SHUTTER_START {}
      AIPARAM C4DAIP_OBQ_ANGULARCAMERA_SHUTTER_END {}
      AIPARAM C4DAIP_OBQ_ANGULARCAMERA_SHUTTER_TYPE {}
      AIPARAM C4DAIP_OBQ_ANGULARCAMERA_SHUTTER_CURVE {}
    }
  }
}

